import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('le tracker reste léger et respecte les signaux de confidentialité',()=>{const s=read('public/analytics.js');assert.ok(Buffer.byteLength(s)<45000);assert.match(s,/globalPrivacyControl/);assert.match(s,/doNotTrack/);assert.doesNotMatch(s,/service_role|SUPABASE_SERVICE_ROLE_KEY/);assert.match(s,/CreatixAnalytics/);});
test('la base est additive, privée et conserve les archives',()=>{const s=read('supabase/migrations/20260825190000_create_cr3atix_analytix.sql');for(const t of ['analytics_projects','analytics_events','analytics_sessions','analytics_daily_stats','analytics_errors','analytics_performance','analytics_campaigns','analytics_health','analytics_alerts'])assert.match(s,new RegExp(`create table if not exists public\\.${t}`));assert.doesNotMatch(s,/drop table|truncate/i);assert.match(s,/enable row level security/g);assert.match(s,/status='ARCHIVED'/);});
test('la collecte passe uniquement par une Edge Function validée',()=>{const s=read('supabase/functions/analytix-collect/index.ts');assert.match(s,/origin_not_allowed/);assert.match(s,/payload_too_large/);assert.match(s,/rate_limited/);assert.match(s,/analytics_ingest_batch/);assert.doesNotMatch(s,/sb_secret_|service_role\s*[:=]\s*['"]/i);});
test('les erreurs JavaScript utilisent pgcrypto depuis un search_path fixe',()=>{const s=read('supabase/migrations/20260825213500_fix_analytix_error_fingerprinting.sql');assert.match(s,/alter function public\.analytics_ingest_batch/);assert.match(s,/public, extensions, pg_temp/);assert.doesNotMatch(s,/drop|truncate/i);});
test('GitHub Pages utilise Node 22, un chemin relatif et noindex',()=>{assert.match(read('.github/workflows/deploy-pages.yml'),/node-version: 22/);assert.match(read('vite.config.ts'),/base: '\.\/'/);assert.match(read('index.html'),/noindex,nofollow/);});
test('les événements jeux demandés sont exposés',()=>{const s=read('src/App.tsx');for(const e of ['game_start','game_end','level_start','level_complete','score','boss_start','boss_defeated','power_used','ultimate_used','install','fullscreen','game_time'])assert.match(s,new RegExp(e));});
test('le heartbeat mesure l’engagement sans fabriquer de game_time',()=>{const s=read('public/analytics.js');assert.match(s,/track\('engagement'/);assert.match(s,/},60000\)/);assert.doesNotMatch(s,/setInterval\([^\n]*track\('game_time'/);});
test('le cockpit couvre comparaison, période personnalisée et campagnes UTM',()=>{const s=read('src/App.tsx');assert.match(s,/previous_daily/);assert.match(s,/Personnalisée/);for(const field of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term'])assert.match(s,new RegExp(field));assert.match(s,/vs période préc\./);});
test('un projet archivé réapparu est réactivé sans ouvrir les fonctions internes',()=>{const s=read('supabase/migrations/20260826151914_restore_archived_analytics_projects.sql');assert.match(s,/analytics_enabled=case when analytics_projects\.status='ARCHIVED' then true/);assert.match(s,/status=case when analytics_projects\.status='ARCHIVED' then 'PENDING'/);assert.match(s,/revoke all on function analytix_private\.sync_projects_from_map/);assert.doesNotMatch(s,/drop table|truncate/i);});
